In [4]:
import numpy as np

In [6]:
array =np.array([1,2,3])
print(array)

[1 2 3]


In [13]:
array2 =np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(array2.shape)

(15,)


In [14]:
a = array2.reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
print("shape :",a.shape)

shape : (3, 5)


In [19]:
print("Dimension :",a.ndim)

Dimension : 2


In [20]:
print("Data type :", a.dtype.name)

Data type : int64


In [21]:
print("Size :",a.size)

Size : 15


In [22]:
print("Type :",type(a))

Type : <class 'numpy.ndarray'>


In [24]:
array3 = np.array([ [1,2,3,4] , [5,6,7,8] , [9,10,11,12] , [13,14,15,16] ])

In [25]:
print(array3)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [27]:
print(array3.shape)

(4, 4)


In [28]:
zeros = np.zeros((3,4))
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [31]:
zeros[1,2] = 3
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 0.]]


In [32]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [34]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [36]:
a = np.linspace(0,10,20)
print(a)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [37]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(b**2)

[5 7 9]
[-3 -3 -3]
[16 25 36]


In [38]:
liste = [1,2,4,5]
array = np.array([2,43,5,435])
print(liste)
print(array)

[1, 2, 4, 5]
[  2  43   5 435]


In [39]:
a = np.array([1,2,3,4])
b = a
c = a
b[0] = 5
print(a , b, c)

[5 2 3 4] [5 2 3 4] [5 2 3 4]


In [40]:
a[0] = 5
d = a.copy()
print(d)

[5 2 3 4]


In [41]:
d

array([5, 2, 3, 4])

In [42]:
a = np.array([1,2,3,4,5,6,7,8])
a[0]
a[0:4]
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1])

In [43]:
b = np.array([[1,2,3,4] , [5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
print(b[1,2])

7


In [45]:
print(b[: , 3])

[4 8]


In [46]:
b[1 , :]

array([5, 6, 7, 8])

In [47]:
b[1 , 1:4]

array([6, 7, 8])

In [48]:
b[: , -1]

array([4, 8])

In [49]:
b[-1 ,:]

array([5, 6, 7, 8])

In [50]:
b = b.ravel()
print(b)

[1 2 3 4 5 6 7 8]


In [51]:
b.T

array([1, 2, 3, 4, 5, 6, 7, 8])